export const MOVIES = [
  { id: 1, title: 'The Shawshank Redemption', genre: 'Drama' },
  { id: 2, title: 'The Godfather', genre: 'Crime' },
  { id: 3, title: 'The Dark Knight', genre: 'Action' },
  { id: 4, title: 'Pulp Fiction', genre: 'Crime' },
  { id: 5, title: 'Forrest Gump', genre: 'Drama' },
  { id: 6, title: 'Inception', genre: 'Sci-Fi' },
  { id: 7, title: 'Fight Club', genre: 'Drama' },
  {
    id: 8,
    title: 'The Lord of the Rings: The Return of the King',
    genre: 'Fantasy',
  },
  { id: 9, title: 'The Matrix', genre: 'Sci-Fi' },
  { id: 10, title: 'Goodfellas', genre: 'Crime' },
  { id: 11, title: 'The Silence of the Lambs', genre: 'Thriller' },
  { id: 12, title: 'Saving Private Ryan', genre: 'War' },
  { id: 13, title: 'The Usual Suspects', genre: 'Crime' },
  { id: 14, title: "Schindler's List", genre: 'History' },
  { id: 15, title: 'The Lion King', genre: 'Animation' },
  { id: 16, title: 'Interstellar', genre: 'Sci-Fi' },
  { id: 17, title: 'Parasite', genre: 'Thriller' },
  { id: 18, title: 'Gladiator', genre: 'Action' },
  { id: 19, title: 'The Departed', genre: 'Crime' },
  { id: 20, title: 'Titanic', genre: 'Romance' },
];
